### ISSUE TITLE
Display of Lights/Switches in the ConfigUI

### ISSUE THREAD

**Issue by Gordon-Newell** [chriscn/homebridge-mihome4u#5]
**Describe the bug**
In the Homebridge Config UI all lights/switches are displayed as "Switch"
 in the Accessories Screen. Ideally this should display as the Switch Name as setup in the MiHome app/website

**To Reproduce**
Setup your devices in the MiHome App or Website.
Install/configure the plug to access your account.
Restart Homebridge
Go to the Accessories tab and observe the MiHome Devices
All devices are displaying as "Switch"

**Expected behavior**
Expect to see the devices listed as per the name setup on MiHome

**Screenshots**
<img width="1428" alt="MiHome Accessories" src="https://user-images.githubusercontent.com/57922876/80913192-a68b7b80-8d3a-11ea-9a58-70d93cf0f809.png">

**Plugin versions:**
homebridge-config-ui-x v4.17.1
homebridge-mihome4u v0.0.5

**Comment by chriscn** [comment]
Do they display the correct name in Home?

**Comment by Gordon-Newell** [comment]
Yes in Home they are fine

**Comment by Gordon-Newell** [comment]
Issues appears to be resolved now, closing.
