### ISSUE TITLE
MiHome configured switch with apostrophe in name is truncated

### ISSUE THREAD

**Issue by Gordon-Newell** [chriscn/homebridge-mihome4u#6]
**Describe the bug**
I have a light with an apostrophe in the name "Aurora's Light" This displays correctly on the MiHome website/app, but the name is truncated in Hombridge UI and on Home

**To Reproduce**

- Create a device with an apostrophe in the name on the MiHome Website/app
- Restart Homebridge to register the device
- Observe the Name in the Homebridge Accessories tab and in iOS home app.
eg "Aurora's Light" is truncated to "Aurora"

**Expected behavior**
Full name is displayed including the apostrophe

**Screenshots**
<img width="1012" alt="Screenshot 2020-05-03 at 21 29 15" src="https://user-images.githubusercontent.com/57922876/80925106-2c341900-8d85-11ea-9e9a-94e9e036c942.png">

<img width="1428" alt="Screenshot 2020-05-03 at 21 21 52" src="https://user-images.githubusercontent.com/57922876/80924979-2c7fe480-8d84-11ea-8ffd-66ecf0b04bae.png">

![IMG_1565](https://user-images.githubusercontent.com/57922876/80925054-b4fe8500-8d84-11ea-92d0-4adc8756457a.jpeg)

**Versions:**
Homebridge 1.0.4
homebridge-config-ui-x v4.17.1
homebridge-mihome4u v0.0.5

**Comment by Gordon-Newell** [comment]
To resolve this issue we need to change the 
`          const friendlyName: string = this.toTitleCase(
            device.label.match(/(?:\d{3}-\d{2} )?([\w -]+)/)[1] || device.label,
`

to 
`          const friendlyName: string = this.toTitleCase(
            device.label.match(/(?:\d{3}-\d{2} )?([\w - ' ’]+)/)[1] || device.label,
`

@chriscn what were you attempting to achieve with the regex?  Wondering if there is something different that can be used.

**Comment by chriscn** [comment]
Hi Gordon. Will get this fixed tomorrow and release a new version :-)

**Comment by chriscn** [comment]
@Gordon-Newell for my MiHome devices we use a 5 digit naming convention as we have around 40. Which have the ID's 123-01 for room 123 device 01. These are ugly and I wanted to remove them from my home to cleanup the names. Which is why I remove them.

**Comment by Gordon-Newell** [comment]
@chriscn, maybe the answer is to put the regex into the config, that would work globally then if people aren't using the same naming.

**Comment by chriscn** [comment]
That is a good idea! I'm gonna open an issue for that and work on that tomorrow. I have also added you as an Author to the repo so that you now have edit access. 

Will also setup automatic deployment from the master branch so when that is pushed npm will push a new update. So I'll work on the develop branch from now on. :-)
